replicaCount: 1

image:
  repository: "ghcr.io/dxas90/learn-node-ui"
  pullPolicy: "IfNotPresent"
  tag: "latest"

service:
  type: "ClusterIP"
  port: 80

namespace: "default"

httproute:
  enabled: False
  gatewayName: "gateway"
  gatewayNamespace: "gateway-system"
  hostnames:
    - "example.local"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - port: 80

persistence:
  enabled: False
  capacity: "8Mi"
  mountPath: "/data"

autoscaling:
  enabled: False
  minReplicas: 1
  maxReplicas: 100

resources:
  limits:
    cpu: 1m
    memory: 64Mi
  requests:
    cpu: 1m
    memory: 64Mi

chart:
  label: "learn-ui"

# Environment configuration
env:
  # Environment variables from file will be loaded here during chart generation
  # if env_file_path is provided in cookiecutter.json
  variables:
    NODE_ENV: "production"
    FIXME_API_URL: "http://learn-node-api.default.svc.cluster.local:3000"

# Other values from the original chart are intentionally left as defaults.
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podSecurityContext:
  fsGroup: 1001
  runAsUser: 1001
  runAsGroup: 1001

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1001

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 3
  periodSeconds: 3
  failureThreshold: 2

readinessProbe:
  tcpSocket:
    port: 80
  initialDelaySeconds: 5
  periodSeconds: 10

# Volume mounts for nginx writable directories (required for readOnlyRootFilesystem)
volumeMounts:
  - name: nginx-cache
    mountPath: /var/cache/nginx
  - name: nginx-run
    mountPath: /var/run
  - name: nginx-tmp
    mountPath: /tmp

# Volumes for nginx writable directories (emptyDir for temporary storage)
volumes:
  - name: nginx-cache
    emptyDir: {}
  - name: nginx-run
    emptyDir: {}
  - name: nginx-tmp
    emptyDir: {}
